// src/pages/TicketsPage.vue
<script setup lang="ts">
import { computed, ref } from "vue";
import { useRouter } from "vue-router";
import { storeToRefs } from "pinia";
import {
  CalendarDays,
  Eye,
  PencilLine,
  Plus,
  Search,
  User,
  X,
} from "lucide-vue-next";

import AppBadge from "@/components/ui/Badge.vue";
import AppButton from "@/components/ui/Button.vue";
import AppCard from "@/components/ui/Card.vue";
import CardContent from "@/components/ui/CardContent.vue";
import CardHeader from "@/components/ui/CardHeader.vue";
import CardTitle from "@/components/ui/CardTitle.vue";
import {
  useTicketStore,
  type TicketPriority,
  type TicketStatus,
} from "@/stores/tickets";

const router = useRouter();
const ticketStore = useTicketStore();
const { tickets } = storeToRefs(ticketStore);

type StatusFilter = "all" | TicketStatus;
type PriorityFilter = "all" | TicketPriority;

const statusFilter = ref<StatusFilter>("all");
const priorityFilter = ref<PriorityFilter>("all");
const searchQuery = ref("");

const statusLabels: Record<TicketStatus, string> = {
  open: "Open",
  in_progress: "In Progress",
  closed: "Closed",
};

const priorityLabels: Record<TicketPriority, string> = {
  low: "Low",
  medium: "Medium",
  high: "High",
  critical: "Critical",
};

const priorityBadgeClasses: Record<TicketPriority, string> = {
  low: "border border-green-200 bg-green-50 text-green-700",
  medium: "border border-yellow-200 bg-yellow-50 text-yellow-700",
  high: "border border-orange-200 bg-orange-50 text-orange-700",
  critical: "border border-red-200 bg-red-50 text-red-700",
};

const statusBadgeClasses: Record<TicketStatus, string> = {
  open: "bg-green-100 text-green-700",
  in_progress: "bg-amber-100 text-amber-700",
  closed: "bg-gray-100 text-gray-700",
};

const sortedTickets = computed(() =>
  [...tickets.value].sort(
    (a, b) => new Date(b.updatedAt).getTime() - new Date(a.updatedAt).getTime()
  )
);

const filteredTickets = computed(() =>
  sortedTickets.value.filter((ticket) => {
    const matchesStatus =
      statusFilter.value === "all" || ticket.status === statusFilter.value;
    const matchesPriority =
      priorityFilter.value === "all" ||
      ticket.priority === priorityFilter.value;

    if (!matchesStatus || !matchesPriority) {
      return false;
    }

    const query = searchQuery.value.trim().toLowerCase();
    if (!query) {
      return true;
    }

    return (
      ticket.title.toLowerCase().includes(query) ||
      ticket.description.toLowerCase().includes(query) ||
      ticket.assignee.toLowerCase().includes(query)
    );
  })
);

const statusCounts = computed(() =>
  tickets.value.reduce(
    (acc, ticket) => {
      acc.total += 1;
      acc[ticket.status] += 1;
      return acc;
    },
    { total: 0, open: 0, in_progress: 0, closed: 0 } as Record<
      "total" | TicketStatus,
      number
    >
  )
);

const hasActiveFilters = computed(
  () =>
    statusFilter.value !== "all" ||
    priorityFilter.value !== "all" ||
    searchQuery.value.trim().length > 0
);

const handleCreate = () => {
  router.push({ name: "ticket-create" });
};

const handleView = (id: string) => {
  router.push({ name: "ticket-detail", params: { id } });
};

const handleEdit = (id: string) => {
  router.push({ name: "ticket-edit", params: { id } });
};

const resetFilters = () => {
  statusFilter.value = "all";
  priorityFilter.value = "all";
  searchQuery.value = "";
};

const formatDate = (value: Date) =>
  new Date(value).toLocaleDateString(undefined, {
    month: "short",
    day: "numeric",
    year: "numeric",
  });

const statusFilterOptions: Array<{ value: StatusFilter; label: string }> = [
  { value: "all", label: "All" },
  { value: "open", label: statusLabels.open },
  { value: "in_progress", label: statusLabels.in_progress },
  { value: "closed", label: statusLabels.closed },
];

const priorityFilterOptions: Array<{ value: PriorityFilter; label: string }> = [
  { value: "all", label: "All priorities" },
  { value: "low", label: priorityLabels.low },
  { value: "medium", label: priorityLabels.medium },
  { value: "high", label: priorityLabels.high },
  { value: "critical", label: priorityLabels.critical },
];

const getStatusCount = (value: StatusFilter) =>
  value === "all" ? statusCounts.value.total : statusCounts.value[value];
</script>

<template>
  <section class="py-16">
    <div class="mx-auto w-full max-w-[1440px] px-4">
      <div
        class="mb-10 flex flex-col gap-6 sm:flex-row sm:items-center sm:justify-between"
      >
        <div>
          <h2 class="text-3xl font-semibold text-foreground">Tickets</h2>
          <p class="mt-2 text-sm text-muted-foreground">
            Manage your support queue, filter by status or priority, and jump
            into any ticket.
          </p>
        </div>
        <AppButton class="gap-2 bg-black text-white" @click="handleCreate">
          <Plus class="h-4 w-4" />
          New Ticket
        </AppButton>
      </div>

      <div
        class="mb-8 flex flex-col gap-4 rounded-2xl bg-transparent md:flex-row md:items-center md:justify-between"
      >
        <p class="text-sm text-muted-foreground">
          Showing {{ filteredTickets.length }} of {{ statusCounts.total }}
          {{ statusCounts.total === 1 ? "ticket" : "tickets" }}
        </p>
        <div class="flex flex-wrap items-center gap-2 md:justify-end">
          <AppButton
            v-for="option in statusFilterOptions"
            :key="option.value"
            variant="outline"
            size="sm"
            class="rounded-full border border-border bg-white/90 px-4 capitalize text-sm font-medium text-muted-foreground shadow-sm backdrop-blur"
            :class="
              statusFilter === option.value
                ? 'border-blue-500 bg-blue-50 text-blue-700 shadow-md'
                : ''
            "
            @click="statusFilter = option.value"
          >
            {{ option.label }}
            <span class="ml-2 text-xs text-muted-foreground/80">
              {{ getStatusCount(option.value) }}
            </span>
          </AppButton>

          <div class="hidden h-5 w-px bg-border md:block" aria-hidden="true" />

          <select
            v-model="priorityFilter"
            class="h-9 rounded-full border border-border bg-white/90 px-4 text-sm text-foreground shadow-sm outline-none transition-[color,box-shadow] focus-visible:border-blue-500 focus-visible:ring-blue-200/60 focus-visible:ring-[3px]"
          >
            <option
              v-for="option in priorityFilterOptions"
              :key="option.value"
              :value="option.value"
            >
              {{ option.label }}
            </option>
          </select>

          <div class="relative w-full min-w-[220px] sm:w-auto">
            <Search
              class="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground"
            />
            <input
              v-model="searchQuery"
              type="search"
              placeholder="Search tickets"
              class="h-9 w-full rounded-full border border-border bg-white/90 pl-10 pr-3 text-sm text-foreground shadow-sm outline-none transition-[color,box-shadow] focus-visible:border-blue-500 focus-visible:ring-blue-200/60 focus-visible:ring-[3px]"
            />
          </div>

          <AppButton
            v-if="hasActiveFilters"
            variant="ghost"
            size="sm"
            class="rounded-full text-sm text-muted-foreground hover:text-foreground"
            @click="resetFilters"
          >
            <X class="h-4 w-4" />
            Clear
          </AppButton>
        </div>
      </div>

      <div
        v-if="filteredTickets.length === 0"
        class="rounded-2xl border border-dashed border-border bg-card/60 p-12 text-center"
      >
        <h3 class="text-lg font-semibold text-foreground">No tickets found</h3>
        <p class="mt-2 text-sm text-muted-foreground">
          Try adjusting your filters or create a new ticket to get started.
        </p>
        <AppButton class="mt-6 gap-2 bg-black text-white" @click="handleCreate">
          <Plus class="h-4 w-4" />
          Create Ticket
        </AppButton>
      </div>

      <div v-else class="grid gap-5 lg:grid-cols-3">
        <AppCard
          v-for="ticket in filteredTickets"
          :key="ticket.id"
          class="flex flex-col justify-between rounded-2xl border border-gray-200 shadow-lg transition hover:-translate-y-1 hover:shadow-xl"
        >
          <CardHeader class="space-y-2">
            <div class="flex flex-wrap items-center gap-3">
              <AppBadge
                variant="secondary"
                :class="statusBadgeClasses[ticket.status]"
              >
                {{ statusLabels[ticket.status] }}
              </AppBadge>
              <AppBadge
                variant="secondary"
                :class="priorityBadgeClasses[ticket.priority]"
              >
                {{ priorityLabels[ticket.priority] }} Priority
              </AppBadge>
            </div>
            <CardTitle class="text-xl text-foreground">
              {{ ticket.title }}
            </CardTitle>
            <p
              class="text-sm leading-relaxed text-muted-foreground line-clamp-3"
            >
              {{ ticket.description }}
            </p>
          </CardHeader>
          <CardContent class="space-y-6">
            <div
              class="flex gap-3 flex-col text-sm text-muted-foreground sm:grid-cols-2"
            >
              <div class="flex items-center gap-2">
                <User class="h-4 w-4" />
                <div>
                  <!-- <p
                    class="text-xs uppercase tracking-wide text-muted-foreground"
                  >
                    Assignee
                  </p> -->
                  <p class="text-foreground">{{ ticket.assignee }}</p>
                </div>
              </div>
              <div class="flex items-center gap-2">
                <CalendarDays class="h-4 w-4" />
                <div>
                  <!-- <p
                    class="text-xs uppercase tracking-wide text-muted-foreground"
                  >
                    Updated
                  </p> -->
                  <p class="text-foreground">
                    {{ formatDate(ticket.updatedAt) }}
                  </p>
                </div>
              </div>
            </div>

            <div
              class="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between"
            >
              <!-- <p class="text-xs text-muted-foreground">
                Created {{ formatDate(ticket.createdAt) }} • Ticket ID #{{
                  ticket.id
                }}
              </p> -->
              <div class="flex gap-2">
                <AppButton
                  size="sm"
                  variant="outline"
                  class="gap-2 border border-gray-200 "
                  @click="handleView(ticket.id)"
                >
                  <Eye class="h-4 w-4" />
                  View
                </AppButton>
                <AppButton
                  size="sm"
                  class="gap-2 text-blac border border-gray-200"
                  @click="handleEdit(ticket.id)"
                >
                  <PencilLine class="h-4 w-4" />
                  <!-- Edit -->
                </AppButton>
              </div>
            </div>
          </CardContent>
        </AppCard>
      </div>
    </div>
  </section>
</template>

// TicketsPage.tsx
import React, { useMemo, useState } from "react";
import { useTickets, TicketStatus } from "../tickets/TicketContext";
import { Button } from "../ui/button";
import { Input } from "../ui/input";
import { Card, CardContent } from "../ui/card";
import { Badge } from "../ui/badge";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "../ui/select";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "../ui/alert-dialog";
import {
  Plus,
  Search,
  Filter,
  Eye,
  Edit,
  Trash2,
  Calendar,
  User,
} from "lucide-react";
import { toast } from "sonner";
import { notifyError } from "../../lib/errorHandling";

interface TicketsPageProps {
  onNavigate: (page: string, ticketId?: string) => void;
}

export const TicketsPage: React.FC<TicketsPageProps> = ({ onNavigate }) => {
  const { tickets, deleteTicket } = useTickets();
  const [searchQuery, setSearchQuery] = useState("");
  const [statusFilter, setStatusFilter] = useState<"all" | TicketStatus>("all");
  const [priorityFilter, setPriorityFilter] = useState<string>("all");
  const [deleteDialogOpen, setDeleteDialogOpen] = useState(false);
  const [ticketToDelete, setTicketToDelete] = useState<string | null>(null);

  const STATUS_LABELS: Record<TicketStatus, string> = {
    open: "Open",
    in_progress: "In Progress",
    closed: "Closed",
  };

  const getStatusColor = (status: TicketStatus) => {
    switch (status) {
      case "open":
        return "bg-green-100 text-green-700";
      case "in_progress":
        return "bg-amber-100 text-amber-700";
      case "closed":
        return "bg-gray-100 text-gray-700";
      default:
        return "bg-gray-100 text-gray-700";
    }
  };

  const getPriorityColor = (priority: string) => {
    switch (priority) {
      case "low":
        return "border-green-500 text-green-700";
      case "medium":
        return "border-yellow-500 text-yellow-700";
      case "high":
        return "border-orange-500 text-orange-700";
      case "critical":
        return "border-red-500 text-red-700";
      default:
        return "border-gray-500 text-gray-700";
    }
  };

  const [loadError, setLoadError] = useState<string | null>(null);

  const filteredTickets = useMemo(() => {
    try {
      const normalizedQuery = searchQuery.toLowerCase();
      return tickets.filter((ticket) => {
        const matchesSearch =
          ticket.title.toLowerCase().includes(normalizedQuery) ||
          ticket.description.toLowerCase().includes(normalizedQuery);
        const matchesStatus =
          statusFilter === "all" || ticket.status === statusFilter;
        const matchesPriority =
          priorityFilter === "all" || ticket.priority === priorityFilter;

        return matchesSearch && matchesStatus && matchesPriority;
      });
    } catch (error) {
      const message = notifyError(
        error,
        "Failed to load tickets. Please retry."
      );
      setLoadError(message);
      return [];
    }
  }, [tickets, searchQuery, statusFilter, priorityFilter]);

  const handleDeleteClick = (id: string) => {
    setTicketToDelete(id);
    setDeleteDialogOpen(true);
  };

  const handleDeleteConfirm = () => {
    if (ticketToDelete) {
      try {
        deleteTicket(ticketToDelete);
        toast.success("Ticket deleted successfully", {
          description: "The ticket has been removed from the system.",
        });
      } catch (error) {
        notifyError(error, "Failed to delete ticket. Please retry.");
      }
      setDeleteDialogOpen(false);
      setTicketToDelete(null);
    }
  };

  return (
    <div className="min-h-[calc(100vh-4rem)] bg-gray-50 py-8">
      <div className="mx-auto w-full max-w-[1440px] px-4">
        <div className="mb-8 flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
          <div>
            <h1 className="mb-2">All Tickets</h1>
            <p className="text-gray-600">
              Manage and track all your support tickets
            </p>
          </div>
          <Button onClick={() => onNavigate("ticket-form")} className="gap-2">
            <Plus className="h-4 w-4" />
            New Ticket
          </Button>
        </div>

        {/* Filters */}
        <div className="mb-6 grid gap-4 md:grid-cols-3">
          <div className="relative">
            <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-gray-400" />
            <Input
              placeholder="Search tickets..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="pl-10"
            />
          </div>

          <Select
            value={statusFilter}
            onValueChange={(value: "all" | TicketStatus) =>
              setStatusFilter(value)
            }
          >
            <SelectTrigger>
              <div className="flex items-center gap-2">
                <Filter className="h-4 w-4" />
                <SelectValue placeholder="Filter by status" />
              </div>
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">All Statuses</SelectItem>
              <SelectItem value="open">Open</SelectItem>
              <SelectItem value="in_progress">In Progress</SelectItem>
              <SelectItem value="closed">Closed</SelectItem>
            </SelectContent>
          </Select>

          <Select value={priorityFilter} onValueChange={setPriorityFilter}>
            <SelectTrigger>
              <div className="flex items-center gap-2">
                <Filter className="h-4 w-4" />
                <SelectValue placeholder="Filter by priority" />
              </div>
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">All Priorities</SelectItem>
              <SelectItem value="low">Low</SelectItem>
              <SelectItem value="medium">Medium</SelectItem>
              <SelectItem value="high">High</SelectItem>
              <SelectItem value="critical">Critical</SelectItem>
            </SelectContent>
          </Select>
        </div>

        {/* Results count */}
        <div className="mb-4 text-sm text-gray-600">
          {loadError ? (
            <span className="text-red-600">{loadError}</span>
          ) : (
            <>
              Showing {filteredTickets.length} of {tickets.length} tickets
            </>
          )}
        </div>

        {/* Tickets Grid */}
        {filteredTickets.length > 0 ? (
          <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
            {filteredTickets.map((ticket) => (
              <Card
                key={ticket.id}
                className="rounded-2xl shadow-lg transition-all hover:shadow-xl"
              >
                <CardContent className="p-6">
                  <div className="mb-4 flex items-start justify-between gap-2">
                    <h3 className="line-clamp-2">{ticket.title}</h3>
                    <Badge className={getStatusColor(ticket.status)}>
                      {STATUS_LABELS[ticket.status]}
                    </Badge>
                  </div>

                  <p className="mb-4 line-clamp-2 text-gray-600">
                    {ticket.description}
                  </p>

                  <div className="mb-4 flex flex-wrap gap-2">
                    <Badge
                      variant="outline"
                      className={getPriorityColor(ticket.priority)}
                    >
                      {ticket.priority}
                    </Badge>
                  </div>

                  <div className="mb-4 space-y-2 text-sm text-gray-600">
                    <div className="flex items-center gap-2">
                      <User className="h-4 w-4" />
                      <span>{ticket.assignee}</span>
                    </div>
                    <div className="flex items-center gap-2">
                      <Calendar className="h-4 w-4" />
                      <span>
                        {new Date(ticket.createdAt).toLocaleDateString()}
                      </span>
                    </div>
                  </div>

                  <div className="flex gap-2">
                    <Button
                      size="sm"
                      variant="outline"
                      onClick={() => onNavigate("ticket-detail", ticket.id)}
                      className="flex-1 gap-1"
                    >
                      <Eye className="h-4 w-4" />
                      View
                    </Button>
                    <Button
                      size="sm"
                      variant="outline"
                      onClick={() => onNavigate("ticket-form", ticket.id)}
                      className="gap-1"
                    >
                      <Edit className="h-4 w-4" />
                    </Button>
                    <Button
                      size="sm"
                      variant="outline"
                      onClick={() => handleDeleteClick(ticket.id)}
                      className="gap-1 text-red-600 hover:bg-red-50 hover:text-red-700"
                    >
                      <Trash2 className="h-4 w-4" />
                    </Button>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        ) : (
          <div className="flex flex-col items-center justify-center rounded-2xl border-2 border-dashed bg-white py-16 shadow-lg">
            <div className="mb-4 rounded-full bg-gray-100 p-6">
              <Search className="h-12 w-12 text-gray-400" />
            </div>
            <h3 className="mb-2">No tickets found</h3>
            <p className="mb-6 text-gray-600">
              Try adjusting your search or filter criteria
            </p>
            <Button
              onClick={() => {
                setSearchQuery("");
                setStatusFilter("all");
                setPriorityFilter("all");
              }}
            >
              Clear Filters
            </Button>
          </div>
        )}

        {/* Delete Confirmation Dialog */}
        <AlertDialog open={deleteDialogOpen} onOpenChange={setDeleteDialogOpen}>
          <AlertDialogContent>
            <AlertDialogHeader>
              <AlertDialogTitle>Are you sure?</AlertDialogTitle>
              <AlertDialogDescription>
                This action cannot be undone. This will permanently delete the
                ticket and remove it from our servers.
              </AlertDialogDescription>
            </AlertDialogHeader>
            <AlertDialogFooter>
              <AlertDialogCancel>Cancel</AlertDialogCancel>
              <AlertDialogAction
                onClick={handleDeleteConfirm}
                className="bg-red-600 hover:bg-red-700"
              >
                Delete
              </AlertDialogAction>
            </AlertDialogFooter>
          </AlertDialogContent>
        </AlertDialog>
      </div>
    </div>
  );
};
